# Generated by Django 4.1.1 on 2023-05-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_email_verified',
        ),
        migrations.AddField(
            model_name='profile',
            name='pis_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
