# Generated by Django 4.1.1 on 2023-05-30 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_is_email_verified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='pis_email_verified',
            new_name='is_email_verified',
        ),
    ]
