# Generated by Django 4.1.1 on 2023-06-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stocks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
